Teste inicial (erro Chrome Driver)
Tentei rodar a api para abrir o WhatsApp via Chrome Driver, porém, está gerando um erro: 
WebDriverException: Message: 'chromedriver' executable needs to be in PATH.